name: Build

on:
  pull_request:
    branches:
    - main
    types: [ closed ]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_UAT }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY_UAT }}
        port: ${{ secrets.EC2_PORT }}
        timeout: 3m
        script: |
          cd tara
          rm -rf node-js-dev-ops
          git clone https://github.com/tara122333/node-js-dev-ops.git
          cd node-js-dev-ops
          npm install
          npm run start

